# Fly.io deployment configuration for Skin Tone Color Analyzer

app = "skin-tone-analyzer"
primary_region = "dfw"

[build]

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "skin_tone_data"
  destination = "/app/temp_images"